# Generated by Django 3.1.7 on 2021-04-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalmatch',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='totalwinmoney',
            field=models.CharField(default=12, max_length=10),
            preserve_default=False,
        ),
    ]
