# Generated by Django 3.1.7 on 2021-04-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210425_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roomid',
            field=models.CharField(default=25, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='roompassword',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
