# Generated by Django 3.1.7 on 2021-04-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_winnings'),
    ]

    operations = [
        migrations.CreateModel(
            name='matchschedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=5)),
                ('soloplayers', models.CharField(max_length=10)),
                ('squadlayers', models.CharField(max_length=10)),
                ('duoteams', models.CharField(max_length=10)),
                ('solowinprize', models.CharField(max_length=10)),
                ('squadwinprize', models.CharField(max_length=10)),
                ('duowinprize', models.CharField(max_length=10)),
                ('soloentryfee', models.CharField(max_length=10)),
                ('squadentryfee', models.CharField(max_length=10)),
                ('duoentryfee', models.CharField(max_length=10)),
            ],
        ),
    ]
