# Generated by Django 3.1.7 on 2021-04-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchregis', '0004_auto_20210427_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='duomatchregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duocharacterid1', models.CharField(max_length=20)),
                ('duocharacterid2', models.CharField(max_length=20)),
                ('duotransid', models.CharField(max_length=100)),
                ('duophone', models.CharField(max_length=50)),
            ],
        ),
    ]
