# Generated by Django 3.1.7 on 2021-04-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchregis', '0006_auto_20210427_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duomatchregistration',
            old_name='duotransid',
            new_name='duotransactionid',
        ),
    ]
