# Generated by Django 3.1.7 on 2021-04-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchregis', '0007_auto_20210427_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='squadmatchregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squadcharacterid1', models.CharField(max_length=20)),
                ('squadcharacterid2', models.CharField(max_length=20)),
                ('squadcharacterid3', models.CharField(max_length=20)),
                ('squadcharacterid4', models.CharField(max_length=20)),
                ('squadtransactionid', models.CharField(max_length=100)),
                ('squadphone', models.CharField(max_length=50)),
            ],
        ),
    ]
